In [1]:
# Importa as bibliotecas
import pandas as pd # Dataframe
import numpy as np # Numeros

# Atribui o arquivo a uma variavel
my_file = "heart.csv"

# Cria o dataframe
df = pd.read_csv(my_file)
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [2]:
# Verifica colunas no caso de resultados faltantes ou incompletos
for column in df.columns.values.tolist():
  total = df[column].isna().sum()
  if total > 1:
    print(f"{column} possui {total} resultados faltantes")

In [3]:
# Sexo para bool
df['Sex'] = df['Sex'].map({'F': 0, 'M': 1})

# ChestPainType (One Hot Encoding)
dummy_variable = pd.get_dummies(df['ChestPainType'], prefix='ChestPain')
df = pd.concat([df, dummy_variable], axis=1)
df.drop('ChestPainType', axis=1, inplace=True)

# RestingECG (One Hot Encoding)
dummy_variable2 = pd.get_dummies(df['RestingECG'], prefix='RestingECG')
df = pd.concat([df, dummy_variable2], axis=1)
df.drop('RestingECG', axis=1, inplace=True)

# ExerciseAngina para bool
df['ExerciseAngina'] = df['ExerciseAngina'].map({'N': 0, 'Y': 1})

# ST_Slope (One Hot Encoding)
dummy_variable3 = pd.get_dummies(df['ST_Slope'], prefix='ST_Slope')
df = pd.concat([df, dummy_variable3], axis=1)
df.drop('ST_Slope', axis=1, inplace=True)

df.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPain_ASY,ChestPain_ATA,ChestPain_NAP,ChestPain_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,False,True,False,False,False,True,False,False,False,True
1,49,0,160,180,0,156,0,1.0,1,False,False,True,False,False,True,False,False,True,False
2,37,1,130,283,0,98,0,0.0,0,False,True,False,False,False,False,True,False,False,True
3,48,0,138,214,0,108,1,1.5,1,True,False,False,False,False,True,False,False,True,False
4,54,1,150,195,0,122,0,0.0,0,False,False,True,False,False,True,False,False,False,True

In [4]:
# Finaliza o tratamento dos dados e salva em um novo arquivo
path = "heart_encoded.csv"
df.to_csv(path, index=False)

In [5]:
# Importa as bibliotecas
import pandas as pd # Dataframe
from sklearn.model_selection import train_test_split # Divisão dos dados
from sklearn.linear_model import LogisticRegression # Regressão Logística
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix # Métricas

df = pd.read_csv("heart_encoded.csv")
df.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPain_ASY,ChestPain_ATA,ChestPain_NAP,ChestPain_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,False,True,False,False,False,True,False,False,False,True
1,49,0,160,180,0,156,0,1.0,1,False,False,True,False,False,True,False,False,True,False
2,37,1,130,283,0,98,0,0.0,0,False,True,False,False,False,False,True,False,False,True
3,48,0,138,214,0,108,1,1.5,1,True,False,False,False,False,True,False,False,True,False
4,54,1,150,195,0,122,0,0.0,0,False,False,True,False,False,True,False,False,False,True

In [6]:
# Separar variáveis independentes (x) e dependente (y)
x = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']

# Dividir os dados em conjuntos de treinamento e teste (80% treino, 20% teste)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Criar e treinar o modelo de Regressão Logística
model = LogisticRegression()
model.fit(x_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [7]:
# Fazer previsões no conjunto de teste
y_pred = model.predict(x_test)
print("\n--- Métricas de Avaliação ---")
print(f"Acurácia: {accuracy_score(y_test, y_pred):.2f}")
print("\n--- Relatório de Classificação ---")
print(classification_report(y_test, y_pred))
print("\n--- Matriz de Confusão ---")
print(confusion_matrix(y_test, y_pred))

--- Métricas de Avaliação ---
Acurácia: 0.86

--- Relatório de Classificação ---
              precision    recall  f1-score   support

           0       0.82      0.87      0.84        77
           1       0.90      0.86      0.88       107

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.87      0.86      0.86       184


--- Matriz de Confusão ---
[[67 10]
 [15 92]]

In [8]:
# Criação do paciente manualmente
novo_paciente = {
    'Age': 43,
    'Sex': 'M',
    'ChestPainType': 'ASY',
    'RestingBP': 130,
    'Cholesterol': 330,
    'FastingBS': 1,
    'RestingECG': 'LVH',
    'MaxHR': 120,
    'ExerciseAngina': 'Y',
    'Oldpeak': 1,
    'ST_Slope': 'Down'
}

# Conferindo o paciente
novo_paciente = pd.DataFrame([novo_paciente])
novo_paciente.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,43,M,ASY,130,330,1,LVH,120,Y,1,Down

In [9]:
# Trabalhando os dados
novo_paciente['Sex'] = novo_paciente['Sex'].map({'F': 0, 'M': 1})

novo_paciente['ExerciseAngina'] = novo_paciente['ExerciseAngina'].map({'N': 0, 'Y': 1})

novo_paciente = pd.concat([novo_paciente, pd.get_dummies(novo_paciente['ChestPainType'], prefix='ChestPain')], axis=1)
novo_paciente.drop('ChestPainType', axis=1, inplace=True)

novo_paciente = pd.concat([novo_paciente, pd.get_dummies(novo_paciente['RestingECG'], prefix='RestingECG')], axis=1)
novo_paciente.drop('RestingECG', axis=1, inplace=True)

novo_paciente = pd.concat([novo_paciente, pd.get_dummies(novo_paciente['ST_Slope'], prefix='ST_Slope')], axis=1)
novo_paciente.drop('ST_Slope', axis=1, inplace=True)

# Reindexando para confirmar a ordem e valores exatos das colunas
novo_paciente = novo_paciente.reindex(columns=x_train.columns, fill_value=0)

novo_paciente.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ChestPain_ASY,ChestPain_ATA,ChestPain_NAP,ChestPain_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,43,1,130,330,1,120,1,1,True,0,0,0,True,0,0,True,0,0

In [10]:

previsao = model.predict(novo_paciente)

if previsao:
  print(f"A previsão é: {previsao[0]} - Tem Doença Cardíaca")
else:
  print(f"A previsão é: {previsao[0]} - Não Tem Doença Cardíaca")

A previsão é: 1 - Tem Doença Cardíaca